// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdyckKmuklEB8GikSb8WK-DNl2LbvHnfI',
    appId: '1:1033621220909:web:777bf4b5dd9059fd5392a4',
    messagingSenderId: '1033621220909',
    projectId: 'eatatcanteen1',
    authDomain: 'eatatcanteen1.firebaseapp.com',
    databaseURL: 'https://eatatcanteen1-default-rtdb.firebaseio.com',
    storageBucket: 'eatatcanteen1.appspot.com',
    measurementId: 'G-S6KQC0CED4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB3e-xUUngdI-eR0lwnzXqs3Ymgn_6R_4',
    appId: '1:1033621220909:android:c601726da6205f5f5392a4',
    messagingSenderId: '1033621220909',
    projectId: 'eatatcanteen1',
    databaseURL: 'https://eatatcanteen1-default-rtdb.firebaseio.com',
    storageBucket: 'eatatcanteen1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN02byLtKY-AsLUFgth1C_soKMClUJ3po',
    appId: '1:1033621220909:ios:aa45c59899f488a05392a4',
    messagingSenderId: '1033621220909',
    projectId: 'eatatcanteen1',
    databaseURL: 'https://eatatcanteen1-default-rtdb.firebaseio.com',
    storageBucket: 'eatatcanteen1.appspot.com',
    iosBundleId: 'com.example.flutterFirebase1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDN02byLtKY-AsLUFgth1C_soKMClUJ3po',
    appId: '1:1033621220909:ios:aa45c59899f488a05392a4',
    messagingSenderId: '1033621220909',
    projectId: 'eatatcanteen1',
    databaseURL: 'https://eatatcanteen1-default-rtdb.firebaseio.com',
    storageBucket: 'eatatcanteen1.appspot.com',
    iosBundleId: 'com.example.flutterFirebase1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdyckKmuklEB8GikSb8WK-DNl2LbvHnfI',
    appId: '1:1033621220909:web:161be69293ab272c5392a4',
    messagingSenderId: '1033621220909',
    projectId: 'eatatcanteen1',
    authDomain: 'eatatcanteen1.firebaseapp.com',
    databaseURL: 'https://eatatcanteen1-default-rtdb.firebaseio.com',
    storageBucket: 'eatatcanteen1.appspot.com',
    measurementId: 'G-KMPNW1WSX7',
  );
}
